# Model
model: "sawyer_push.xml"

# Contact pairs
npair: 4 		# number of contact pairs
spair1: [4,4,4,4]	# indices of the sites on the robot
spair2: [0,1,2,3]	# indices of the corresponding sites in the environment

# Task
## desired final pose of the control joint
desiredFinalPos: [1.25, 0, 0.0647, 0.0, 0.0, 0.0]
## desired final velocity of the control and robot joints
desiredFinalVel: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
## initial index of the DOF associated with the control joint
controlJointDOF0: 0

# Weights
w1: 1e3		# weight on deviations in x and y directions
w2: 0e0		# weight on deviations in z and orientation
w3: 1e0		# weight on final velocities
w4: 8e-2	# weight on virtual stiffness

# Simulation
tf: 1.00	# [s] final time
tc: 5e-2	# [s] control sampling period
